Ensure IDX doc is created and linked to DID
3box/identity-wallet-js pull request #73
Opened 2020-09-10 15:53 UTC by PaulLeCam

2020-09-10 16:00 UTC, oed approved these changes
Looks good. Feel free to update the `DID` prop to `id`.

2020-09-11 07:43 UTC, oed requested changes
One thing is missing here. The `addAuthEntries` method must now check to make sure that the authKeychain is in the root index.

2020-09-11 07:43 UTC, oed commented on src/identity-wallet.ts
> +   * @property {string} id                 The 3ID of the IdentityWallet instance
```suggestion
   * @property {string} id                 The DID of the IdentityWallet instance
```

2020-09-11 10:09 UTC, PaulLeCam commented
@oed good point, thanks for catching this!
I made the change so that the auth keychain doc is always created even if empty, this should cover the case.

2020-09-11 12:11 UTC, oed approved these changes
Thanks for the update. Lmk if you need a release directly!

2020-09-11 12:12 UTC, merged

2020-09-11 12:25 UTC, PaulLeCam commented
Thanks! It's not a blocker for me at the moment but might be helpful for the community to have a new release.